### PR TITLE
cli git additions

### LINKED ISSUE #214: `vapor new` should automatically initialize an empty Git repository
The `vapor new` command downloads a tarball of the official example and extracts it.

The command should initialize an empty Git repository in the newly created directory by default. Providing the optional command line flag `--without-git` (other suggestions welcome) to `vapor new` provides an option to not initialize an empty repository.

### LINKED ISSUE #216: improve git functionality for `vapor new`
Currently every project created with vapor new is based on the vapor example project. That results in boilerplate code which is more suitable for demonstration purposes than actual starting ground for new projects. In example the mustache example functionality and dependency likely is going to be removed every time.

The solution would be to introduce the example argument for the vapor command line application, which creates an new project based on the example.
In parallel the new argument will be modified to create a barebone project with just the minimal content necessary to get going (requires a new repository as a source). In addition there is an option (argument `--template`, other suggestions welcome) to specify the repository to use as the template for creating a new project.

This enables new starting points when creating new projects.

# Example

    vapor new Vaporizer

Creates a new project in the `Vaporizer` directory based on the minimal, default project template. Invokes dependency installation and build automatically (`vapor build`).

    vapor new Vaporizer --template=https://github.com/alomvar/vapor-blog-template

Creates a new project in the `Vaporizer` directory based on the provided project template (a Git repository). Invokes dependency installation and build automatically (`vapor build`).

    vapor example

Creates a new project in `VaporExample` based on the official Vapor example project. Invokes dependency installation and build automatically (`vapor build`) **and runs it afterwards**.

### PR DESCRIPTION
**Pull request by alomvar**
`vapor new` now automatically initializes an empty Git repository in the newly created project. Added optional `--without-git` flag to prevent this behavior.

Closes #216.

### CODE REVIEW

**Comment by alomvar** [comment]
Oops, now I see: I should have named the pull request more descriptive.

**Comment by LoganWright** [comment]
Looks good to me, resolve conflicts and we'll get this merged 👍

**Comment by alomvar** [comment]
`0.8` was tagged, so this can finally join the party. 🎉

**Comment by tannernelson** [comment]
I'm clearing the milestone off of this because additions to the CLI aren't affected by tag. As soon as they hit master, they are referenced by `cli.qutheory.io`.

**Pull request merged**
