### PR TITLE
snapshot 05-09

### PR DESCRIPTION
**Pull request by tannernelson**
WIP

### CODE REVIEW

**Comment by adamstener** [comment]
I'm not able to run on this snapshot, there seems to be an error in Strand.swift
/hello-world/Packages/Strand-1.2.3/Sources/Strand.swift:55:53: Cannot convert value of type '(arg: UnsafeMutablePointer<Void>!) -> UnsafeMutablePointer<Void>!' to expected argument type '(@convention(c) (UnsafeMutablePointer<Void>?) -> UnsafeMutablePointer<Void>?)!'

**Comment by LoganWright** [comment]
@adamstener Right now, w/ version `0.8.x`, you should use the `2016-05-03` toolchain. We're working on getting 05-09 support on this branch, but are waiting for some dependencies among other things.

Keep an eye on this PR for when to move to 05-09!

**Comment by tannernelson** [comment]
There is a bug in `05-09` that prevents Vapor from compiling release. We're going to skip this snapshot. https://bugs.swift.org/browse/SR-1457

**Comment by Evertt** [comment]
Does anyone know when the next snapshot will be? I thought there was already a change in there that make `.self` unnecessary already. I'm not sure if that's correct, but if it is, then I'm eager to work with the next snapshot. :-D

**Comment by tannernelson** [comment]
I don't know, hopefully soon!

**Pull request merged**
