### PR TITLE
Added `Dockerfile` and `Makefile` to build a docker image based on `.…

### PR DESCRIPTION
**Pull request by feinstruktur**
…swift-version. The `Makefile` is really only a helper to make the build command more accessible.

### CODE REVIEW

**Comment by feinstruktur** [comment]
There was a [discussion in slack](https://qutheory.slack.com/archives/general/p1463935809003155) about adapting the swift docker `Dockerfile` and build it using `.swift-version`.

This is what this does. I've just thrown it in the top level dir as is. It could probably be better integrated and also map a volume into the container. This PR is probably more a starting point for a discussion about how to best integrate this.

**Comment by feinstruktur** [comment]
I've chosen the route of having an `ARG` in the `Dockerfile` and using `--build-arg` to change it when building, which is picked up by the `Makefile` automatically.

Another option would be to `ADD` the swift version file `.swift-version` and set the environment variable from it with a `RUN` command. The advantage being that it's all happening within the `Dockerfile`.

The downside is that you can't adjust the version via an argument, just by updating the `.swift-version` file. (Although it would be possible to set the env from the file and have an overrider via a `--build-arg`.)

**Comment by tannernelson** [comment]
@LoganWright gets back from a vacation tomorrow. I'd like to talk with him about including this functionality into the Vapor CLI.

I'm imagining something like `vapor docker init` `vapor docker push` etc.

**Comment by LoganWright** [comment]
@tannernelson I was thinking the same thing, do you have much xp with Docker? We seem to have a few people who use it in the community, so we'll definitely have to lean on them for support.

@feinstruktur just for reference, here's our cli: https://github.com/qutheory/vapor-cli

I know the file is long! It's scripted right now, we'll likely move to something compiled soon, but just to give you an idea of what we're thinking. I think docker should have it's own subcommand structure similar to the way heroku does. Ideally in the future, we can support most major hosting frameworks.

**Comment by feinstruktur** [comment]
I see what you mean. That would allow us to get rid of the `Makefile` as well, essentially just putting the make targets in `vapor` under slightly different names:

`build` -> `init`
`run` -> `run`? I didn't see a `run` or anything similar for `heroku` in the script, I suppose that's WIP?
`enter` -> `enter` for now? It's probably useful to have for debugging (it starts a `bash` shell inside the container)

Regarding `build` - this will take quite a while to execute (of the order of a few minutes on my MBP). It would be faster if we pulled pre-built and tagged images from Dockerhub here. However, that then means

- to set up an account at Dockerhub
- maintain the images

It's probably something to consider for later. Also, with Docker's ability to provision containers on infrastructure directly (AWS, Digital Ocean, etc) it should be possible to extend this to deploy there directly via a `vapor` command.

I should have some time later today and I'll have a look into adding those initial `docker` subcommands.

**Comment by feinstruktur** [comment]
Closing this, superseded by https://github.com/qutheory/vapor-cli/pull/7

**Pull request closed without merging**
