### PR TITLE
Updated to Swift 3.0 Snapshot 04-25

### PR DESCRIPTION
**Pull request by czechboy0**
Small changes, but will require a minor version bump as they're not backwards compatible.

### CODE REVIEW

**Comment by LoganWright** [comment]
Looks good to me 👍

**Comment by czechboy0** [comment]
@LoganWright CI passed, merge if happy

**Comment by LoganWright** [comment]
@czechboy0 does Hummingbird need to update?

**Comment by czechboy0** [comment]
Not as far as I know, only warnings upstream.

**Comment by ketzusaka** [comment]
No, Hummingbird is fine. I think there are warnings from C7, but we can fix the warnings in a patch probably?

**Comment by tannernelson** [comment]
Awesome, thanks @czechboy0.

We upped our dependencies with CryptoKitten, so that makes me think this will need a minor bump.

**Comment by czechboy0** [comment]
@tannernelson Does that mean I need to change something? I thought only a git tag will be affected.

**Comment by tannernelson** [comment]
Nope you're good. Looks like we'll tag this as 0.7.

**Pull request merged**
