### PR TITLE
Make session data access more direct

### PR DESCRIPTION
**Pull request by ketzusaka**
Minor change to make session access more direct & abstract the underlying data structure

### CODE REVIEW

**Comment by tannernelson** [comment]
I'm a fan of the symmetry here:

```swift
request.data["key"]
request.parameters["key"]
request.session["key"]
```

What would be the benefit to changing this?

**Comment by ketzusaka** [comment]
@tannernelson Right now you have to do:
```
request.session.data["key"]
```

This PR makes it:
```
request.session["key"]
```

**Comment by tannernelson** [comment]
Omg I was reading it the wrong way.

**Comment by tannernelson** [comment]
This is a great change :+1:

**Comment by ketzusaka** [comment]
@tannernelson haha all good! I did update the readme, but I think you'll have to update the wiki to reflect it.

**Comment by tannernelson** [comment]
Done. Thank you.

**Pull request merged**
