### PR TITLE
Created bridge that inherits from StringInitializable

### PR DESCRIPTION
**Pull request by Evertt**
#315 #316

### CODE REVIEW

**Comment by tannernelson** [comment]
I have no idea what's going on here. Maybe @LoganWright has an idea. Seems like the compiler is getting confused about the Extractable protocol.

**Comment by Evertt** [comment]
Compiler bug of this snapshot maybe?

**Comment by Evertt** [comment]
Shall I otherwise just put this change directly on the master branch?

**Comment by LoganWright** [comment]
The issue here is importing Fluent which redeclares extractable. I don't see the syntax changing at all, should we consider moving Extractable to its own module?

**Comment by tannernelson** [comment]
I guess we need to move extractable. Maybe into PathIndexable or a separate module?

**Comment by Evertt** [comment]
This still cannot be fully merged?

**Comment by LoganWright** [comment]
@Evertt we're still not passing tests on this branch, but have started the work of centralizing some of the offenders which will resolve this.

**Pull request merged**
