### PR TITLE
adding status convenience initializer #126

### PR DESCRIPTION
**Pull request by LoganWright**
#126

### CODE REVIEW

**Comment by tannernelson** [comment]
I think the body should be empty here. `text: ""`

**Comment by LoganWright** [comment]
@tannernelson The issue has the reason as the text, it might be nice to have it visible from browsers or clients that way, not sure what's ideal.

**Comment by tannernelson** [comment]
From the point of view of someone who works with APIs a lot, if the API returns a string randomly when it normally returns JSON or XML or something that would confuse me. If you don't explicitly include some message to send, I think the body should be empty. Unless someone knows of a more official requirement, this is what I think I've seen most personally.

**Comment by tannernelson** [comment]
This is too behind to merge. But I will add this manually.

**Pull request closed without merging**
