### PR TITLE
attempt to use NSJSON

### PR DESCRIPTION
**Pull request by tannernelson**

### CODE REVIEW

**Comment by czechboy0** [comment]
Why do you want to move to NSJSON? 😊 Performance?

**Comment by czechboy0** [comment]
Also - are you migrating *away* from C7's JSON type?

**Comment by tannernelson** [comment]
@czechboy0 mainly to minimize dependencies.

**Comment by czechboy0** [comment]
Although the dropping of C7's JSON type is unfortunate. Will break projects that rely on that interoperability between frameworks.

**Comment by Danappelxx** [comment]
Are you planning to bridge between Foundation and C7 JSON? Seems like that wouldn't be too difficult while still keeping the cross-project interoperability.

**Comment by tannernelson** [comment]
We want more control over the public API for Vapor, like the ability to use our Polymorphic and PathIndexable packages extensively. C7.JSON has been creating issues for us here. We will continue to support Open Swift through C7.JSONRepresentable conformance.

**Comment by czechboy0** [comment]
@tannernelson What exactly is the issue with it? I think we should fix those issues in C7 instead of dumping support for it. I've been investing time into supporting C7/S4 in my projects in the past months, so it'd be sad to see the reverse happening here (and arguably the whole point of Open Swift would have to be brought into question).

**Comment by esummers** [comment]
Was Freddy (as in Freddy vs JSON) considered?  I think it has the most swifty API out of all the JSON frameworks I've tried and is fast when error handling is considered in the benchmarks.  It implements its own parser that does not depend on NSJSONSerialization.   https://www.bignerdranch.com/blog/introducing-freddy-an-open-source-framework-for-parsing-json-in-swift/

**Pull request merged**
