### PR TITLE
RFC for converting Session into a protocol/SessionDriver publicly conformable

### PR DESCRIPTION
**Pull request by ketzusaka**
This allows people to make their own drivers and session types.

This has a number of implications. I'll do my best to provide the reasoning behind these.

Firstly, conforming to a Middleware now means conforming to an instance method instead of a class method. This stemmed originally from trying to restrict SessionDriver to a generic type, but as I pulled that out into just a protocol, I found we would still have to do some odd Swift things to make it work correctly. One thought was to make the SessionDriver a class variable, but it would have to be an optional type since the SessionDriver isn't know until an Application is configured. However, having a variable with shared state like that is not preferable, especially for testability, and I felt it left too much responsibility to the Application class, as it would need to ensure it set that variable instead of simply adding a new Middleware. All in all, I think instance-based middlewares are the way to go, and Providers should be converted to a typealias of a function signature, which would allow closures, global functions, and methods to be used as Providers, so I feel like a divergence between these two concepts is expected.

Secondly, SessionMiddleware is now responsibile for creating the identifier to represent the session. I thought this was appropriate as it is what reads and sets this value into the users cookies, and how we build the session key doesn't really matter to implementors of Session or SessionDriver.

Thirdly, Request's Session reference is now an optional. The original implementation was automatically set to an instance of Session, which was a class, and forced memory-based sessions. Since Sessions are not created until the pass of the SessionMiddleware we can't define the session as non-optional. If we moved session creation outside of the middleware and right before the Request is created we could make it non-optional, but I felt like that was too much for this PR and may move too much responsibility to the ServerDriver, but that can be discussed more.

Looking forward to hearing the feedback on this. I think the next step after making SessionDriver/Session a protocol is figuring out a good way to store other types besides a String inside the session.

### CODE REVIEW

**Comment by tannernelson** [comment]
I like some of the changes here, but I don't like getting rid of the `Session` class or making `var session` on the `Request` an optional. I think `Session` should work like `Hash` or `Log` does, where there is a statically accessed facade that has an instance of the underlying driver. 

This way Sessions can be opened, closed, created, and destroyed without having to interface with the underlying Driver. This would also match more closely with how Laravel works. 

In terms of making Providers and Middleware instance based, I think we should continue passing types. Even if we decide to initialize them internally. But I would be interested in @LoganWright and @czechboy0 opinion on this. I'm sure there are performance / memory implications that we should consider as well. In terms of how Laravel does this, the class is passed to the app, but the handle function is an instance method. So there is internal initialization going on.

**Comment by ketzusaka** [comment]
@tannernelson Thanks for the feedback. I think I thought of a good way to keep `Session` a class, non-optional in `Request`, and provide a static reference in the driver, and probably change back the `Middleware` stuff. I'll update this to match shortly. If that approach is liked, i'll make a new PR with just those changes.

For `Providers`s, I was thinking of just having them be a function reference instead of having an instance method. That way people could add them as arbitrary closures like routers. Just a thought, though!

Thanks for the feedback.

**Comment by ketzusaka** [comment]
Ok, i've updated this. Most of the original implications can no longer apply. :)

**Comment by tannernelson** [comment]
This looks a lot better. The one thing I'm thinking is that perhaps the SessionDriver should be responsible for generating the identifying token? I could see some implementations wanting a different format, or possibly someone wanting to make those cookie tokens more secure.

**Comment by ketzusaka** [comment]
Yeah, that makes sense; ill update it.

**Comment by tannernelson** [comment]
Thinking more about the middleware: Since middleware is not initialized with every request, it seems like it makes more sense to pass the `Type` and have `static` methods. This is more clear to anyone writing middleware that if they want to store a member variable, it's going to be a static member variable that will persist between requests. If this persistence isn't clear, it could be a security vulnerability (devs assuming sensitive information will get deallocated at the end of a request). 

The other side of that would be `init`ing a new instance with each request. This seems like it could get slow in a big application with potentially 10-20 on each request.

Furthermore, middleware, at least how I've always known it, is for very simple filtering on requests and responses. There is usually never more than a few lines, and almost never member variables. But it's possible I haven't been using them to their full potential.

**Comment by ketzusaka** [comment]
Thinking about it more as well, middleware probably is better stateless between requests, so passing in an initialized middleware should be avoided. If someone really needs state throughout the processing of the handle call, they can create an object internally. 

I do feel that both Providers and Middlewares would be best served as a typealias now. I think that's always best when you're expecting a single static function signature

**Comment by ketzusaka** [comment]
I'm going to close this as I think we've nailed down a direction regarding the session stuff, and the middleware chat can be moved to slack.

**Pull request closed without merging**
