### PR TITLE
Fluent model bridge

### PR DESCRIPTION
**Pull request by Evertt**
#315

### CODE REVIEW

**Comment by Evertt** [comment]
It seems like the travis build failure has little to do with my code. I'll try updating the branch, maybe that will help.

**Comment by Evertt** [comment]
Can anybody explain to me how I can make the build pass?

**Comment by tannernelson** [comment]
I'm trying to figure it out myself.

If you could move the branch to `qutheory/vapor:fluent-model-bridge` I could test it on my computer and see what is happening.

**Comment by Evertt** [comment]
@tannernelson #322

**Pull request closed without merging**
