### PR TITLE
Add support for route specific middleware

### PR DESCRIPTION
**Pull request by chaselatta**
This is a proposal/basic implementation to support route specific middleware. I have not added tests and have only done minimal work to get this working because I wanted to get feedback before pursuing this any further. 

The main points are that that we would add a new struct `RouteDescriptor` which contains information about the route. The `RouteDriver` protocol would then be updated to register and return the `RouteDescriptor` object instead of the `Request.Handler`.

The `Application` has been updated to take a `[Middleware.Type]` array on all of its route registration methods. By defaulting to `[]` on all these methods we don't break any existing code but we do need to update the `BranchRouter` and `Branch` to work directly with the `RouteDescriptor` instead of the handlers.

This allows us to write route definitions like the following:
```swift
app.get("welcome") { _ in
    return "Hello"
}

app.get("user", middlewares: [AuthMiddleware.self]) { _ in
    return [user: user]
}

app.middleware.append(GlobalMiddleware)
```
In the above example we run `GlobalMiddleware` on each request and `AuthMiddleware` on the `/user` request.

Let me know if this is something that you think would be worthwhile and worthy of breaking the `RouteDriver` protocol for and I will clean it up.

### CODE REVIEW

**Comment by tannernelson** [comment]
I like the idea, but I think this could be implemented with much less code.

```swift
app.middleware(AuthenticatedMiddleware) {
  app.get("hello") { request in 
    return "world"
  }

  app.get("other") { ... }

  ...
}
```

```swift
class Application {
  var currentMiddlewareType: Middleware.Type?
  func middleware(middlewareType: Middleware.Type, closure: () -> ()) {
    self.currentMiddlewareType = middlewareType
    closure()
    self.currentMIddlewareType = nil
  }
  public final func add(method: Request.Method, path: String, closure: Handler) {
    if let middleware = self.currentMiddlewareType {
      closure = middleware.handle(closure)
    }

    router.register(hostname: host, method: method, path: path) { request in
        return try closure(request).response()
    }
  }
}
```

**Comment by chaselatta** [comment]
That is an interesting idea and much easier than what I did. I also like that you essentially get route grouping with it. I will play around with it and update the PR.

**Comment by tannernelson** [comment]
There's another PR that changes the layout of this code quite a bit. Probably going to create a nasty merge conflict. 

It will be easier for both of us if I include your code manually into the new PR. But I want you to get credit for your contribution so I'm going to leave it commented out and you can create a PR that uncomments it.  Does that sound OK?

**Comment by chaselatta** [comment]
that works for me.

**Pull request closed without merging**
