### PR TITLE
WIP: Service Provider Support

### PR DESCRIPTION
**Pull request by shnhrrsn**
Working on adding in Provider support for more flexibility with third party packages.

The framework has been refactored a bit, creating an Application class which replaces the old Server class and merging in Route creation.  All existing apps will need to update their `main.swift` apps to look like this:

```swift
let app = Application()

app.get("heartbeat", closure: HeartbeatController().index)

// app.providers.append(SomeProvider)
application.start(port: 8080)
```

## TODO
- [x] Gather feedback
- [ ] Test coverage

## Example

Using VaporStencil as an example, instead of having to include `View.renderers[".stencil"] = StencilRenderer()` in `main.swift`, we could create `StencilProvider`:

```swift
import Vapor

public class StencilProvider: Vapor.Provider {

	public static func boot(application: Application) {
		View.renderers[".stencil"] = StencilRenderer()
	}

}
```

And in main.swift, it would look like:

```swift
let app = Application()
app.providers.append(StencilProvider)
```

See original PR https://github.com/qutheory/vapor/pull/39 for more information.

### CODE REVIEW

**Comment by shnhrrsn** [comment]
@tannernelson Here you go, had to re-submit the PR as I'm not aware of anyway to change the source branch in an existing PR.

**Comment by shnhrrsn** [comment]
@tannernelson The changes you made in f07998a and 096bc62 tie providers directly to the start of the server.  I separated the app/provider booting away from the server start so vapor-console could boot the app and use providers without starting the server.  With those changes providers are essentially inaccessible to console.

**Comment by shnhrrsn** [comment]
It also looks like those changes dropped the ability to specify a different server driver, unsure if that was intentional or not.

**Comment by tannernelson** [comment]
@shnhrrsn Ah okay, I will put those back.

**Comment by tannernelson** [comment]
I updated the middleware and providers to have a similar API. I think using a simple array is best because the user can choose to append to that array, or to replace it with an empty array.

```swift
let app = Application()

app.get("stencil") { request in
    return try View(path: "template.stencil", context: [
        "hello": "world"
    ])
}

app.middleware.append(ErrorMiddleware) //look at ErrorMiddleware below
app.providers.append(StencilProvider)

app.start(port: 8080)
```

Also, with everything converted to `Request.Handler` we can now create Middleware for handling errors like so.

```swift
enum Error: ErrorType {
    case NotFound
}

class ErrorMiddleware: Middleware {
    class func handle(handler: Request.Handler) -> Request.Handler {
        
        return { request in
            
            do {
                let response = try handler(request: request)
                return response
            } catch Error.NotFound {
                return try Response(status: .NotFound, json: [
                    "error": true,
                    "message": "Item not found"
                ])
            }

        }
    }
}
```

So now you can define custom Error types and then throw them wherever you want.

**Comment by tannernelson** [comment]
Let me know what you think of those changes / if I destroyed any other functions that you want put back.

**Comment by shnhrrsn** [comment]
Streamlined Middleware + Provider APIs look good!

I think the changes you made should be fine, going to update everything else to match and I'll report back if I run into any issues.

**Comment by shnhrrsn** [comment]
I ran into an issue with the latest changes: in vapor-console, there's the [ServeCommand](https://github.com/qutheory/vapor-console/blob/master/Sources/ServeCommand.swift). This is going to cause every provider to get booted twice, first when Console tells them to and then again when serve tells the app to start the server.

We could solve this one of two ways:
   1. Re-add the booted flag and add a guard to bootProviders
   2. Merge vapor-console into the main framework and actually run through serve command, which would clean up the process arg looping in Application.start(), since console commands have built in support for options/arguments.

**Comment by tannernelson** [comment]
Is there any issues with booting multiple times?

**Comment by shnhrrsn** [comment]
I think it would depend on how complicated the providers get, for the stencil provider there's just a bit of double allocation going on for `StencilRenderer` which isn't a huge deal.

If we look forward and consider something like events being added to the framework, every time a provider subscribes to one it'll get subscribed twice and now that I think about it.

Now that I think about it, while events right now are a theoretical feature, if they're built on top of something like NSNotificationCenter, this would be the use case for having provider instances instead of using static calls since a provider would need to be allocated to work with NSNotificationCenter.

**Comment by tannernelson** [comment]
I think in that case the provider could just implement an initialized object as a static member variable. Then the NSNotificationCenter could delegate to that object. 

I think we will be fine with double booting on the console for now. I'd rather put effort into merging the console into the main framework.

**Comment by shnhrrsn** [comment]
I'm good with that.

Have we finalized this architecture then or is there still more changes you want to make?

**Comment by tannernelson** [comment]
I'm happy with it. Let's merge tomorrow morning to give @LoganWright and @mpclarkson a chance to look it over.

**Comment by LoganWright** [comment]
Hey all, I just rebased this on top of #47 so we can keep the history cleaner.  There were a bunch of conflicts to resolve, so if going forward, we could use that branch, it'd be easier to not have to repeat ourselves.

I can also push to this branch directly if you'd prefer

**Comment by tannernelson** [comment]
Moved to #52.

**Pull request closed without merging**
