### PR TITLE
controller factories

### PR DESCRIPTION
**Pull request by tannernelson**
moving #124 here.

### CODE REVIEW

**Comment by svanimpe** [comment]
Sorry for the late response, but why did you rename `controllerFactory` to `makeControllerWith`? That doesn't make any sense to me. Parameters are supposed to be named according to their roles. `controllerFactory` seemed like the perfect name as it:
1. makes the role (factory) clear.
2. contains the word `controller` (the base method name `add` doesn't give any information to indicate it accepts controller methods so this adds clarity).
3. it clearly shows the difference with the method that has `controller` parameter.

I have never seen an imperative verb being used in a parameter name. Do you have any examples?

**Comment by LoganWright** [comment]
@svanimpe It's to more closely align w/ Swift 3 api design guidelines which specifies `make` should be used for all factories and creation.

**Comment by svanimpe** [comment]
@LoganWright The design guideline is that the name of the **method** should start with `make` (similar to how other method names use imperative verbs). This has nothing to do whatsoever with parameter names. There is even an explicit example in the guidelines of a factory passed as a parameter that is named `widgetFactory`.

**Comment by LoganWright** [comment]
@svanimpe that example is red as an indication of how not to name in the `Name variables, parameters, and associated types according to their roles` section. Is it used somewhere else as well that I missed?

The suggested example uses the external keyword `from`, so maybe we should adopt that since it's fairly similar usage and have something like `from controllerFactory: () -> Controller`

**Comment by svanimpe** [comment]
@LoganWright Yes, but the 'red' part refers to the `widget` type information, not the `factory` suffix. According to this guideline, we should simply call it `factory` (or `supplier` or whatever) and drop the `controller`, which is what I originally did. I decided to use `controllerFactory` anyway because `factory` does not contain enough information and clarity at the point of use is one of the super-guidelines. The method is simply called `add` so it's not clear from context what exactly the factory is supposed to make.

**Pull request merged**
