### PR TITLE
Update README.md with a code quality badge

### PR DESCRIPTION
**Pull request by grodowski**
Hi! Please consider adding a code quality badge from [codebeat](https://codebeat.co) It should help keep up high quality and allow newcomers dive into the codebase easier by working on refactoring suggested "quick wins". 

[codebeat badge](https://codebeat.co/projects/github-com-qutheory-vapor)

Disclaimer: I'm one of co-authors of codebeat. Please share your feedback!

### CODE REVIEW

**Comment by tannernelson** [comment]
Looks cool, I like it.

**Comment by tannernelson** [comment]
One suggestion I would make is having the badge say "Code Quality". Is that possible? Until more people no what codebeat is that might be confusing.

**Comment by tannernelson** [comment]
For instance, Travis sayins `[build: passing]` not `[travis: passing]`

**Comment by grodowski** [comment]
@tannernelson Thanks for this suggestion, really good point to consider. It already sparked a discussion within our team 😀

**Comment by tannernelson** [comment]
@grodowski Keep me updated on your decision. We are working on a PR now that fixes a lot of the issues giving us a B rating, so I'd like to wait for that to merge this anyway.

In the meantime, do you have any solutions / recommendations for Test Coverage and Documentation Coverage badges for Swift repos?

**Comment by tannernelson** [comment]
Closing this for now. Let me know if you have any updates.

**Comment by grodowski** [comment]
@tannernelson B is not a bad grade! 🙃I'd really like to hear your feedback about codebeat and especially the value of our suggestions ("Quick Wins"). Thank you for supporting us

In terms of code coverage: have you tried https://github.com/realm/SwiftCov.git with https://coveralls.io?

**Comment by tannernelson** [comment]
@grodowski I'm wondering if there is any way to exclude a specific file from Codebeat's analysis? 

We have a generated code (`Sources/Vapor/Core/Generated.swift`) file that powers our type-safe routing and it's lowering our score quite a bit.

**Comment by grodowski** [comment]
@tannernelson Please add a `.codebeatignore` dotfile in the root directory of your repo. You can read more about exclusions in our docs: https://help.codebeat.co/docs/path-exclusions#manual-excludes

**Comment by tannernelson** [comment]
I added the file, but it doesn't appear to be working. Did I type something wrong?

https://github.com/qutheory/vapor/blob/master/.codebeatignore

**Comment by grodowski** [comment]
Congrats for finding a bug in codebeat :bug: :tada: My guess is that's not working because of a trailing whitespace - we're working on a fix!

**Pull request closed without merging**
