### PR TITLE
Protocolize Controller

### PR DESCRIPTION
**Pull request by ketzusaka**
I felt like Controller would be best served as a Protocol with default implementations. This would remove the restriction of subclassing Controller directly.

Unfortunately, I couldn't get the Xcode Project or the unit tests to run, but this does build.

This would be a breaking change for existing implementations of Controller in that they would have to remove their `override` keyword, but I feel like it's not very substantial.

### CODE REVIEW

**Comment by tannernelson** [comment]
This is a lot better.

**Comment by tannernelson** [comment]
Upon implementing, it looks like you are required to add `@objc` functionality if you want to make the protocol optional. Without making it optional, the user is required to implement all of the functions in the protocol. The extension added made it unclear what happens if you don't explicitly add a method in the protocol.

When Swift makes optional protocols possible without `@objc` this can be re-added. And when registering a controller as a `resource()` it would be able to check which optional methods were actually implemented.

**Comment by ketzusaka** [comment]
@tannernelson While you do need `@objc` to provide optional methods, I believe this is still a better approach. With the default implementations you get the same behavior as you would with a class and not overriding the methods.

**Comment by ketzusaka** [comment]
With the protocol extension, if you don't implement your own methods the default methods will be ran. If you do implement them in your class, the default methods are not called, and are never reachable from your class as the requirements are defined in the protocol itself.

**Comment by ketzusaka** [comment]
@tannernelson Also, as all of the required methods have default implementations, you can conform to Controller and obtain all the functionality that was in the class for free.

**Comment by tannernelson** [comment]
I think it's more clear when you see `override` that there are default implementations in the background. If there were no `override` keyword, I would assume no action for unimplemented methods. Which is how the framework should behave. If you don't implement `get()`, nothing should happen if you call the get resource. But until optional protocols are feasible, it should be clear the default controller has default implementations that should be considered and overridden.

**Comment by tannernelson** [comment]
Perhaps the clearest option would be to make `Controller` a protocol and require all methods are implemented. Because without optional protocol methods, something will need to be returned for those routes. And I'd rather have the user choose what is returned for all routes than get surprised by the default behavior (empty string) later.

**Comment by ketzusaka** [comment]
@tannernelson I don't feel as though default implementations are particularly surprising for users. Since Swift 2, they've been heavily pushed on to us through the standard library and most Swift conferences seem to bring them up and talk about them. The biggest thing you lose with default implementations is you don't get the error that the method must be implemented when conforming, but under the Class based approach you wouldn't receive that error (just the responses that the class implements), and if the protocol had all `optional` methods you also wouldn't get that error either. 

I do agree that not returning anything is probably the best option here, though. Default implementations could return a Not Found response so the user could only implement what they want instead of forcing them to do that themselves.

**Comment by tannernelson** [comment]
I like the idea of the default implementation throwing a `NotFound` error. I will look into taht.

**Comment by tannernelson** [comment]
For now i've returned it to a protocol forcing controllers to implement all methods.

**Comment by ketzusaka** [comment]
@tannernelson Thanks! And apologies if that all came off strong. I'm very passionate about protocols haha xD

**Comment by tannernelson** [comment]
Being passionate about good code is nothing to apologize for.

**Pull request merged**
