### PR TITLE
Full cookie serialization

### PR DESCRIPTION
**Pull request by ketzusaka**
This PR moves the responsibility of serializing cookie data to the `Cookie` struct. This is a better separation of concerns in my eyes. The `Cookies` serialization is updated to use the new method on `Cookie`, which fixes an issue where the attributes of a cookie were never set.

There is still the issue where we're folding all of the cookie properties into a single Set-Cookie header, which doesn't seem to work in some browsers; that fix will come in a subsequent PR.

### CODE REVIEW

**Comment by tannernelson** [comment]
@ketzusaka Do you know which browsers don't work with that?

**Comment by ketzusaka** [comment]
@tannernelson I tested specifically on Chrome. I don't believe it was working in safari either as things weren't operating as I expected there, but I'd have to double check on that.

Also, the format for the Expires attribute appears to require a format that would break multiple cookies in a single Set-Cookie header, and that is why it is recommended to use multiple header rows.

**Comment by LoganWright** [comment]
@ketzusaka @tannernelson I added a mini commit on here that will give us multi cookie support until we implement something more comprehensive.

This was tested on Chrome and Safari 👍

**Comment by ketzusaka** [comment]
oh nice, surprised that works haha

**Pull request merged**
