### PR TITLE
fix data split endless loop

### PR DESCRIPTION
**Pull request by qazyn951230**
1. Put a lager file (2.5M) in multipart request, `Data.split` run into endless loop.
2. Data.split seems like have performance problem.
3. Should I add some tests?

ps. Sorry about my English not good.
pps. It''s my first pull request.

### CODE REVIEW

**Comment by tannernelson** [comment]
A test would be awesome! We have had some problems with this method in the past.

**Comment by LoganWright** [comment]
@qazyn951230 do you happen to have a sample of the data that was causing the issue, we could add a quick test in on this.

**Comment by qazyn951230** [comment]
@LoganWright I'm back.
I test some different files(pdf, md, png), any 300KB file will crash it.

**Comment by LoganWright** [comment]
@qazyn951230 I moved your commit to #434 and added a quick test. Once CI passes, we'll get it merged in. Sorry about the delay, and thanks again for contributing to Vapor!

**Pull request closed without merging**
